### ISSUE TITLE
대시보드 화면 API

### ISSUE THREAD

**Issue by YPYP333YPYP** [Link-Cargo/link-cargo-back#42]
## 📌 어떤 EPIC/Milestone 인가요?
대시보드 화면에 대한 API

## 🗓️ Due date
~ 2024-08-19

## 🌈 Feature List
- [x] 포워더에게 가장 저렴한 견적서 추천 기능
- [x] 운임이 가장 저렴할 때 정보 추천 기능
- [x] 항구 혼잡도 관련 정보 조회 기능
- [x] 사용자 관심사에 따른 뉴스 요약 기능
- [x] 포워더가 제시한 견적서 비교 기능
- [x] 운임지수 관련 정보 조회 기능

## ✅ Check List

- [ ] !!트렐로 카드 등록
- [ ] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [ ] DDL 체크
