### ISSUE TITLE
대시보드 전체 수정

### ISSUE THREAD

**Issue by YPYP333YPYP** [Link-Cargo/link-cargo-back#70]
## 📌 어떤 EPIC/Milestone 인가요?
대시보드 API 전체 수정

## 🗓️ Due date
~ 2024.09.26

## 🌈 Feature List
- [x] API 파라미터 수정
- [x] API Response 수정
- [x] API 비즈니스 로직 수정

## ✅ Check List

- [x] !!트렐로 카드 등록
- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
